#!/bin/bash

shopt -s nullglob

from=/data/inbox/
to=/data/games/

for file in ${from}*; do
	if ! find "${file}" -mmin -2 | grep -q ""; then
		clamscan --remove=yes -r "${file}"
		mv "${file}" "${to}"
	fi
done


