#!/bin/bash
# Author: Steyn
#
# /etc/init.d/mount_windows_drive
#
### BEGIN INIT INFO
# Provides:          cod4server
# Required-Start:    $null
# Should-Start:      $null
# Required-Stop:     xdm
# Should-Stop:	     $null
# Default-Start:     5
# Default-Stop:      5
# Short-Description: Start the cod 4 linux server
# Description:       Not actually a service at all.
### END INIT INFO

case "$1" in
   start)
     # use colour for ease of spotting
      echo -e "\E[36mRunning $0 (start)...\E[0m";
      /opt/cod4server/cod4server
      echo -e "\E[36mDone $0 \E[0m";
   ;;
   stop)

      echo "Stop not supporterd ;p"

   ;;
   restart)
      $0 stop
      $0 start
      ;;
   *)
      echo "Usage $0 (start|stop|restart)"
      exit 1; 
      ;;
esac 


